# config/chunking_config.yaml
# Path: config/chunking_config.yaml

# Default chunking strategy
default_strategy: recursive

# Text chunking configuration
text:
  chunk_size: 1000  # Target chunk size in characters
  chunk_overlap: 200  # Overlap between chunks
  separators:  # Separators for recursive splitting (in order of preference)
    - "\n\n"  # Double newline (paragraphs)
    - "\n"    # Single newline
    - ". "    # Sentence end
    - "! "    # Exclamation
    - "? "    # Question
    - "; "    # Semicolon
    - ", "    # Comma
    - " "     # Space
    - ""      # Character level (last resort)
  
  # Token limits
  max_tokens: 400  # Maximum tokens per chunk
  min_tokens: 50   # Minimum tokens per chunk

# PDF-specific configuration
pdf:
  chunk_size: 1500
  chunk_overlap: 300
  extract_images: false
  extract_tables: true

# Markdown-specific configuration  
markdown:
  chunk_size: 1200
  chunk_overlap: 200
  split_on_headers: true
  min_header_level: 2  # Don't split on h1
  preserve_formatting: true

# Document type specific overrides
document_type_config:
  manual:
    chunk_size: 1500
    chunk_overlap: 300
    strategy: recursive
  
  faq:
    chunk_size: 800
    chunk_overlap: 100
    strategy: recursive
    split_on_headers: true
  
  policy:
    chunk_size: 1200
    chunk_overlap: 200
    strategy: recursive
  
  technical:
    chunk_size: 1000
    chunk_overlap: 250
    strategy: recursive
    preserve_code_blocks: true

# Semantic chunking configuration (future enhancement)
semantic:
  enabled: false
  model: "sentence-transformers/all-MiniLM-L6-v2"
  similarity_threshold: 0.8
  min_chunk_size: 200
  max_chunk_size: 2000